server:
  port: 8580

spring:
  application:
    name: cloud-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 30  #租期到期时间
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}

feign:
  hystrix:
    enabled: true
#  compression:
#    request:
#      min-request-size: 2048 #用于设置请求的最小阈值，默认2048
#      enabled: true   #请求进行压缩
#      mime-types: text/xml,application/xml,application/json #用以支持的媒体类型列表，默认
#    response:
#      enabled: true   #响应进行压缩
